[project]
name = "zksync-waterfall"
authors = ["ZKSync Waterfall Team"]
description = "A decentralized subscription management platform on ZKSync"
telemetry = false
requirements = []

[contracts.payment-flow-processor]
path = "contracts/payment-flow-processor.clar"
depends_on = []

[contracts.analytics-insights]
path = "contracts/analytics-insights.clar"
depends_on = []

[contracts.waterfall-manager]
path = "contracts/waterfall-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
